### ISSUE TITLE
Reflect a bug in Caissa1.14.1

### ISSUE THREAD

**Issue by bjyxycl** [Witek902/Caissa#16] opened 2023-11-13 19:39 UTC
3r3k/7p/2Q5/8/2B2PK1/6P1/4P3/5q2 b - - 98 99 
Please forgive me for my poor English. Caissa1.14.1 is very powerful! But there is a bug, the above situation went through Rd8-d4 in the engine league, resulting in one step being killed by the king. I hope to correct it.

**Comment by Witek902** [comment] 2023-11-13 22:28
Hi. Thanks! Do you have full PGN with the game? Where the game was played?

**Comment by Witek902** [comment] 2023-11-13 22:31
Actually, nvm. I know what the issue is. After Rd4 Caissa thinks it's a draw, because half-move count is 100. But it's wrong, because there's mate in one. Will fix that!

**Comment by Witek902** [comment] 2023-11-14 01:57
Fixed in 993063d6bbd3527fa5e86b22801a9a01fe983dcc

**Closed by Witek902** 2023-11-14 01:57 UTC
